// Parses the resume agent's ###-delimited output into a keyed package.
//
// The prompt emits sections as "### Title ###\ncontent", so splitting on ###
// yields alternating [title, content, title, content, ...] pairs. Mapping by
// POSITION is wrong (it grabs titles as content); we map by TITLE instead.
// First occurrence wins, so the clean plain-text sections beat the later
// HTML-duplicated ones. Work history is NOT produced by the agent — it comes
// from MasterContext.

type MC = Record<string, any>

function normalize(t: string): string {
  return t.replace(/<[^>]+>/g, '').replace(/\(.*?\)/g, '').trim().toLowerCase()
}

// Ordered keyword -> field. Checked in order; first matching title sets the field.
const TITLE_MAP: Array<[RegExp, string]> = [
  [/^date$/, 'date'],
  [/target job title|target role/, 'targetRole'],
  [/target company/, 'targetCompany'],
  [/resume summary/, 'resumeSummary'],
  [/^skills\s*1$|^skills1$/, 'skills1'],
  [/^skills\s*2$|^skills2$/, 'skills2'],
  [/^expertise$/, 'expertise'],
  [/relevant skills.*1$|relevant.*bullet.*1/, 'relevant1'],
  [/relevant skills.*2$|relevant.*bullet.*2/, 'relevant2'],
  [/relevant skills.*3$|relevant.*bullet.*3/, 'relevant3'],
  [/cover letter/, 'coverLetter'],
  [/about me\s*1|about me passage 1/, 'aboutMe1'],
  [/about me\s*2|about me passage 2/, 'aboutMe2'],
  [/executive profile/, 'executiveProfile'],
  [/core accomplishments/, 'coreAccomplishments'],
]

export function parseResumePackage(content: string, mc: MC, jobTitle: string, company: string): any {
  const parts = content.split('###').map((s) => s.trim()).filter(Boolean)
  const fields: Record<string, string> = {}

  for (let i = 0; i + 1 < parts.length; i += 2) {
    const title = normalize(parts[i])
    const body = parts[i + 1]
    for (const [rx, key] of TITLE_MAP) {
      if (rx.test(title) && !fields[key]) { fields[key] = body; break }
    }
  }

  const val = (k: string) => (mc && mc[k] != null ? String(mc[k]) : '')

  return {
    date: fields.date || new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' }),
    targetRole: fields.targetRole || jobTitle,
    targetCompany: fields.targetCompany || company,
    resumeSummary: fields.resumeSummary || '',
    skills1: fields.skills1 || '',
    skills2: fields.skills2 || '',
    expertise: fields.expertise || '',
    relevant1: fields.relevant1 || '',
    relevant2: fields.relevant2 || '',
    relevant3: fields.relevant3 || '',
    coverLetter: fields.coverLetter || '',
    aboutMe1: fields.aboutMe1 || '',
    aboutMe2: fields.aboutMe2 || '',
    executiveProfile: fields.executiveProfile || '',
    coreAccomplishments: fields.coreAccomplishments || '',
    // Work history is not generated by the agent — use the baseline MasterContext.
    workHistory1: val('workHistory1'),
    workHistory2: val('workHistory2'),
    workHistory3: val('workHistory3'),
    workHistory4: val('workHistory4'),
    _parsedFieldCount: Object.keys(fields).length
  }
}
