import React, { useState } from 'react'
import { useApp, go } from '../state.jsx'
import { saveDesignSystem } from '../api.js'

function buildCSS(result) {
  const lines = ['/* Generated Design System CSS Custom Properties */\n:root {']
  const prims = result?.variables?.collections?.Primitives
  if (Array.isArray(prims)) {
    prims.forEach((v) => { lines.push(`  --${v.name.replace(/\./g, '-')}: ${v.value};`) })
  }
  const tokens = result?.variables?.collections?.Tokens
  if (Array.isArray(tokens)) {
    tokens.forEach((t) => { lines.push(`  --${t.name.replace(/\./g, '-')}: ${t.lightValue || t.value || 'inherit'};`) })
  }
  lines.push('}')
  if (Array.isArray(tokens) && tokens.some((t) => t.darkValue)) {
    lines.push('\n[data-theme="dark"] {')
    tokens.filter((t) => t.darkValue).forEach((t) => { lines.push(`  --${t.name.replace(/\./g, '-')}: ${t.darkValue};`) })
    lines.push('}')
  }
  return lines.join('\n')
}

function buildTS(result) {
  const lines = ['// Generated Design System TypeScript Constants\n']
  const prims = result?.variables?.collections?.Primitives
  if (Array.isArray(prims)) {
    const colorPrims = prims.filter((v) => v.type === 'color' || v.resolvedType === 'COLOR')
    if (colorPrims.length) {
      lines.push('export const colors = {')
      colorPrims.forEach((v) => { lines.push(`  '${v.name}': '${v.value}',`) })
      lines.push('}\n')
    }
  }
  const styles = result?.styles?.text || []
  if (styles.length) {
    lines.push('export const textStyles = {')
    styles.forEach((s) => { lines.push(`  '${s.name}': { fontFamily: '${s.fontFamily}', fontSize: ${s.fontSize}, fontWeight: ${s.fontWeight} },`) })
    lines.push('}\n')
  }
  lines.push('export const components = ', JSON.stringify(result?.components || [], null, 2))
  return lines.join('\n')
}

function buildPluginReadme(result) {
  return `# Figma Plugin: ${result?.meta?.name || 'Design System'}

## Quick Start
1. Open Figma → Plugins → Development → Import plugin from manifest
2. Select the manifest.json in this folder
3. Run the plugin in a blank Figma file
4. It will create all variables, styles, and components in one run

## Contents
- design-system.json — full token + component schema
- manifest.json — Figma plugin manifest
- src/plugin.ts — orchestrator
- src/variables.ts — variable collections
- src/styles.ts — text/color/effect styles
- src/components.ts — component library

## Build
\`\`\`
npm install
npm run build
\`\`\`

Generated by Design Library Generator
`
}

function buildHandoffPrompt(result) {
  const name = result?.meta?.name || 'MyApp'
  const primary = result?.meta?.primaryColor || '#1B4F5C'
  const fonts = [...new Set((result?.styles?.text || []).map((t) => t.fontFamily).filter(Boolean))].join(', ') || 'Inter'
  const compCount = result?.components?.length || 0
  const tokenCount = (result?.variables?.collections?.Tokens || []).length
  return `Build "${name}" from scratch using the attached SPEC.md as the single source of truth.

Tech stack:
- React + TypeScript + Vite
- Tailwind CSS
- Supabase (auth + database)

Design system — apply exactly:
- Primary brand: ${primary}
- Fonts: ${fonts}
- Page background: ${result?.meta?.bgColor || '#F8F9FA'}
- Card background: #FFFFFF
- Border: #E2E8F0
- Button border radius: 8px
- Card border radius: 12px
- ${compCount} components defined in design-system.json
- ${tokenCount} semantic tokens in design-system.json

Reference design-system.json for all visual values. Never hardcode.

Build phases:
Phase 1 — Shell: routing, layout, sidebar, navigation
Phase 2 — Data: Supabase schema, queries, mutations
Phase 3 — Interactions: forms, modals, state
Phase 4 — Polish: tokens applied, hover states, transitions, empty states

Stop and confirm after each phase.

[paste SPEC.md here]`
}

function download(filename, content, mime = 'text/plain') {
  const blob = new Blob([content], { type: mime })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url; a.download = filename; a.click()
  URL.revokeObjectURL(url)
}

function downloadZip(result) {
  // Build a minimal zip-like bundle — just the JSON and readme in a .zip via manual PKZIP encoding
  // For simplicity, download JSON and readme as separate files
  const name = (result?.meta?.name || 'design-system').toLowerCase().replace(/\s+/g, '-')
  download(`${name}.json`, JSON.stringify(result, null, 2), 'application/json')
  download('FIGMA_PLUGIN_README.md', buildPluginReadme(result), 'text/markdown')
}

export default function Export() {
  const { state, dispatch } = useApp()
  const [copied, setCopied] = useState(false)
  const [saving, setSaving] = useState(false)
  const [saved, setSaved] = useState(false)
  const [saveErr, setSaveErr] = useState('')

  if (!state.result) {
    return (
      <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', gap: 16, padding: 32 }}>
        <div className="t-h2">Nothing to export yet</div>
        <button className="dlg-btn dlg-btn-primary" onClick={() => go('/upload')}>Start Over</button>
      </div>
    )
  }

  const r = state.result
  const name = (r?.meta?.name || state.projectName || 'design-system').toLowerCase().replace(/\s+/g, '-')

  function copyPrompt() {
    navigator.clipboard.writeText(buildHandoffPrompt(r)).catch(() => {})
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  async function handleSave() {
    if (!state.user) { go('/upload'); return }
    setSaving(true); setSaveErr('')
    try {
      const saved = await saveDesignSystem({ ...r, id: r.id || crypto.randomUUID() })
      dispatch({ type: 'ADD_SAVED', system: saved })
      setSaved(true)
    } catch (e) { setSaveErr(e.message) }
    setSaving(false)
  }

  const EXPORTS = [
    {
      icon: '⇓',
      label: 'design-system.json',
      desc: 'Full schema — variables, tokens, styles, components. Feed to the Figma plugin.',
      action: () => download(`${name}.json`, JSON.stringify(r, null, 2), 'application/json'),
      badge: 'Core',
    },
    {
      icon: '◈',
      label: 'tokens.css',
      desc: 'CSS custom properties for light and dark mode. Drop into any web project.',
      action: () => download(`${name}-tokens.css`, buildCSS(r), 'text/css'),
      badge: 'CSS',
    },
    {
      icon: '✦',
      label: 'tokens.ts',
      desc: 'TypeScript constants for type-safe token usage in React/Next apps.',
      action: () => download(`${name}-tokens.ts`, buildTS(r), 'text/typescript'),
      badge: 'TS',
    },
    {
      icon: '▦',
      label: 'Figma Plugin Bundle',
      desc: 'design-system.json + plugin README. Run the plugin to create everything in Figma.',
      action: () => downloadZip(r),
      badge: 'Figma',
    },
  ]

  return (
    <div style={{ maxWidth: 700, margin: '0 auto', padding: '32px 24px' }}>
      <div style={{ marginBottom: 28 }}>
        <h1 className="t-h1" style={{ marginBottom: 6 }}>Export</h1>
        <p className="t-body" style={{ color: 'var(--dlg-text-2)' }}>
          Download your design system in every format, or copy the Claude Code handoff prompt.
        </p>
      </div>

      {/* Save to account */}
      {!saved && (
        <div className="dlg-banner dlg-banner-info" style={{ marginBottom: 24, justifyContent: 'space-between', flexWrap: 'wrap', gap: 10 }}>
          <div>
            <div className="t-sm" style={{ fontWeight: 600 }}>{state.user ? 'Save to your account' : 'Sign in to save'}</div>
            <div className="t-sm">Saved systems appear in the Showcase dropdown for live preview.</div>
          </div>
          <button className="dlg-btn dlg-btn-primary" disabled={saving} onClick={handleSave} style={{ flexShrink: 0 }}>
            {saving ? 'Saving…' : state.user ? 'Save Library' : 'Sign in & Save'}
          </button>
        </div>
      )}
      {saved && <div className="dlg-banner dlg-banner-success" style={{ marginBottom: 24 }}>✓ Saved — visible in Showcase dropdown</div>}
      {saveErr && <div className="dlg-banner dlg-banner-error" style={{ marginBottom: 16 }}>{saveErr}</div>}

      {/* Download cards */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 10, marginBottom: 28 }}>
        {EXPORTS.map((e) => (
          <div key={e.label} className="dlg-card" style={{ padding: '16px 18px', display: 'flex', alignItems: 'center', gap: 14 }}>
            <div style={{ width: 40, height: 40, borderRadius: 10, background: 'var(--dlg-brand-soft)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 20, flexShrink: 0 }}>{e.icon}</div>
            <div style={{ flex: 1, minWidth: 0 }}>
              <div style={{ fontWeight: 600, fontSize: 14, marginBottom: 2, display: 'flex', alignItems: 'center', gap: 8 }}>
                {e.label}
                <span className="dlg-badge dlg-badge-brand" style={{ fontSize: 10 }}>{e.badge}</span>
              </div>
              <div className="t-sm" style={{ color: 'var(--dlg-text-2)' }}>{e.desc}</div>
            </div>
            <button className="dlg-btn dlg-btn-primary" onClick={e.action} style={{ flexShrink: 0, gap: 6 }}>
              ⇓ Download
            </button>
          </div>
        ))}
      </div>

      {/* Claude Code handoff prompt */}
      <div className="dlg-card" style={{ padding: 20 }}>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 12 }}>
          <div>
            <div className="t-h3">Claude Code Handoff Prompt</div>
            <div className="t-sm" style={{ color: 'var(--dlg-text-2)' }}>Paste this at the start of a Claude Code session to build the app with your design system.</div>
          </div>
          <button className="dlg-btn" onClick={copyPrompt} style={{ flexShrink: 0, gap: 6 }}>
            {copied ? '✓ Copied!' : '⊕ Copy'}
          </button>
        </div>
        <pre style={{ background: 'var(--dlg-bg)', border: '1px solid var(--dlg-border)', borderRadius: 8, padding: 14, fontSize: 12, overflow: 'auto', maxHeight: 280, whiteSpace: 'pre-wrap', wordBreak: 'break-word', color: 'var(--dlg-text-2)', fontFamily: 'var(--t-mono, monospace)' }}>
          {buildHandoffPrompt(r)}
        </pre>
      </div>

      <div style={{ display: 'flex', gap: 10, justifyContent: 'flex-end', marginTop: 20 }}>
        <button className="dlg-btn" onClick={() => go('/review')}>← Back to Review</button>
        <button className="dlg-btn dlg-btn-primary" onClick={() => go('/showcase')}>View in Showcase →</button>
      </div>
    </div>
  )
}
